### ISSUE TITLE
Source for Data/Demographics/population.xlsx

### ISSUE THREAD

**Issue by bjornpiltz** [MarcSchneble/Nowcasting-Fatal-COVID-19-Infections#2]
Hi!
Would you mind giving a source for `Data/Demographics/population.xlsx`? It would be very useful and I couldn't find a reference.

Thanks
Björn

**Comment by MarcSchneble** [comment]
The file stems from the "Deutsches Statistisches Bundesamt" (https://www.destatis.de/EN/Home/_node.html).

**Comment by bjornpiltz** [comment]
Thanks! I cannot find that granular age breakdown on [their page](https://www-genesis.destatis.de/genesis/online?operation=statistic&levelindex=0&levelid=1611142946417&code=12111#abreadcrumb). Could you tell me which census it refers to?

**Comment by MarcSchneble** [comment]
It refers to data from the "Deutsches Statistisches Bundesamt" published in 2019. (which are actually based on the census 2011 afaik)
